#!/bin/bash

weakString="Your Password is Weak"
strongPassword="Your password is Strong"

echo -n "Enter your password: "
read password

#minimum length of password must be 8 characters.
if [ ${#password} -lt 8 ]
then
	echo  "$password: $weakString"
	exit
fi

#the password must contain at least numeric character.
if [ `echo $password | grep -c -E "[0-9]+"` -eq 0 ]
then
	echo "$password: $weakString"
	exit
fi

#the password must contain at least one special character.
if [ `echo $password | grep -c -E "[@#$%&*+=-]+"` -eq 0 ]
then
	echo "$password: $weakString"
	exit
fi

echo "$password: $strongPassword"

